/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module au_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input button,
    input start,
    input godmode,
    output reg [15:0] red,
    output reg [15:0] blue,
    output reg [15:0] green,
    output reg [15:0] seg,
    input usb_rx,
    output reg usb_tx
  );
  
  
  
  reg rst;
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_1 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  wire [16-1:0] M_game_red;
  wire [16-1:0] M_game_green;
  wire [16-1:0] M_game_blue;
  wire [8-1:0] M_game_score;
  reg [1-1:0] M_game_button;
  reg [1-1:0] M_game_start;
  reg [1-1:0] M_game_godbtn;
  game_2 game (
    .clk(clk),
    .rst(rst),
    .button(M_game_button),
    .start(M_game_start),
    .godbtn(M_game_godbtn),
    .red(M_game_red),
    .green(M_game_green),
    .blue(M_game_blue),
    .score(M_game_score)
  );
  wire [16-1:0] M_multi_seven_seg_seg;
  reg [8-1:0] M_multi_seven_seg_score;
  multi_seven_seg_3 multi_seven_seg (
    .clk(clk),
    .rst(rst),
    .score(M_multi_seven_seg_score),
    .seg(M_multi_seven_seg_seg)
  );
  
  always @* begin
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    led = 8'h00;
    usb_tx = usb_rx;
    M_game_button = button;
    M_game_start = start;
    M_game_godbtn = godmode;
    red = M_game_red;
    blue = M_game_blue;
    green = M_game_green;
    M_multi_seven_seg_score = M_game_score;
    seg = M_multi_seven_seg_seg;
  end
endmodule
