/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module comparator_12 (
    input [5:0] alufn,
    input [15:0] a,
    input [15:0] b,
    output reg [15:0] op
  );
  
  
  
  always @* begin
    
    case (alufn[0+1-:2])
      2'h1: begin
        op = $signed(a) == $signed(b);
      end
      2'h2: begin
        op = $signed(a) < $signed(b);
      end
      2'h3: begin
        op = $signed(a) <= $signed(b);
      end
      default: begin
        op = 16'h0000;
      end
    endcase
  end
endmodule
