/*
   This file was generated automatically by Alchitry Labs version 1.2.0.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module seven_seg_3 (
    input [3:0] char,
    output reg [7:0] seg
  );
  
  
  
  always @* begin
    
    case (char)
      1'h0: begin
        seg = 7'h3f;
      end
      1'h1: begin
        seg = 7'h06;
      end
      2'h2: begin
        seg = 7'h5b;
      end
      2'h3: begin
        seg = 7'h4f;
      end
      3'h4: begin
        seg = 7'h66;
      end
      3'h5: begin
        seg = 7'h6d;
      end
      3'h6: begin
        seg = 7'h7d;
      end
      3'h7: begin
        seg = 7'h07;
      end
      4'h8: begin
        seg = 7'h7f;
      end
      4'h9: begin
        seg = 7'h6f;
      end
      default: begin
        seg = 7'h00;
      end
    endcase
  end
endmodule
