/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module multi_seven_seg_3 (
    input clk,
    input rst,
    input [7:0] score,
    output reg [15:0] seg
  );
  
  
  
  
  wire [16-1:0] M_mod_alu;
  wire [1-1:0] M_mod_z;
  wire [1-1:0] M_mod_v;
  wire [1-1:0] M_mod_n;
  reg [6-1:0] M_mod_alufn;
  reg [16-1:0] M_mod_a;
  reg [16-1:0] M_mod_b;
  alu_7 mod (
    .alufn(M_mod_alufn),
    .a(M_mod_a),
    .b(M_mod_b),
    .alu(M_mod_alu),
    .z(M_mod_z),
    .v(M_mod_v),
    .n(M_mod_n)
  );
  
  wire [16-1:0] M_div_alu;
  wire [1-1:0] M_div_z;
  wire [1-1:0] M_div_v;
  wire [1-1:0] M_div_n;
  reg [6-1:0] M_div_alufn;
  reg [16-1:0] M_div_a;
  reg [16-1:0] M_div_b;
  alu_7 div (
    .alufn(M_div_alufn),
    .a(M_div_a),
    .b(M_div_b),
    .alu(M_div_alu),
    .z(M_div_z),
    .v(M_div_v),
    .n(M_div_n)
  );
  
  wire [8-1:0] M_seven_seg0_seg;
  reg [4-1:0] M_seven_seg0_char;
  seven_seg_8 seven_seg0 (
    .char(M_seven_seg0_char),
    .seg(M_seven_seg0_seg)
  );
  
  wire [8-1:0] M_seven_seg1_seg;
  reg [4-1:0] M_seven_seg1_char;
  seven_seg_8 seven_seg1 (
    .char(M_seven_seg1_char),
    .seg(M_seven_seg1_seg)
  );
  
  always @* begin
    M_mod_a = score;
    M_mod_b = 4'ha;
    M_mod_alufn = 6'h04;
    M_seven_seg0_char = M_mod_alu[0+3-:4];
    M_div_a = score;
    M_div_b = 4'ha;
    M_div_alufn = 6'h03;
    M_seven_seg1_char = M_div_alu[0+3-:4];
    seg[0+7-:8] = M_seven_seg0_seg;
    seg[8+7-:8] = M_seven_seg1_seg;
  end
endmodule
